font_family JetBrainsMono Nerd Font
font_size 11.5
window_padding_width 14
background_opacity 0.80
background_blur 32
confirm_os_window_close 0
cursor_shape beam
foreground #f7f8fb
background #181b23
selection_background #35547f
color4 #78abff
color5 #c8a7ff
