font_family JetBrainsMono Nerd Font
font_size 11.5
window_padding_width 12
background_opacity 0.88
background_blur 24
confirm_os_window_close 0
cursor_shape beam
foreground #f4f4f6
background #161821
selection_background #44546f
color4 #7aa2f7
color5 #bb9af7
