windowrulev2 = float,class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = float,class:^(blueman-manager)$
windowrulev2 = float,class:^(nm-connection-editor)$
windowrulev2 = float,title:^(Picture-in-Picture)$
windowrulev2 = size 70% 75%,class:^(org.pulseaudio.pavucontrol)$
layerrule = blur,waybar
layerrule = blur,swaync-control-center
layerrule = ignorezero,waybar
