$mod = SUPER
bind = $mod, Return, exec, kitty
bind = $mod, Space, exec, walker
bind = $mod SHIFT, Space, exec, ~/.config/walker/scripts/recent-files.sh
bind = $mod SHIFT, S, exec, ~/.config/walker/scripts/settings-search.sh
bind = $mod SHIFT, A, exec, ~/.config/walker/scripts/quick-actions.sh
bind = $mod, Q, killactive
bind = $mod, F, fullscreen
bind = $mod, L, exec, loginctl lock-session
bind = $mod, E, exec, thunar
bind = $mod, B, exec, ~/.config/dock/scripts/dock.sh show
bind = $mod, comma, exec, hyprsequoia-settings
bind = $mod SHIFT, C, exec, swaync-client -t -sw
bind = $mod SHIFT, E, exit
bind = $mod, V, togglefloating
bind = $mod, left, movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up, movefocus, u
bind = $mod, down, movefocus, d
bind = , Print, exec, hyprsequoia-screenshot region
bind = SHIFT, Print, exec, hyprsequoia-screenshot screen
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = , XF86MonBrightnessUp, exec, brightnessctl set 5%+
bindel = , XF86MonBrightnessDown, exec, brightnessctl set 5%-
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
