general {
    hide_cursor = true
}
background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
}
label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    font_size = 78
    color = rgba(ffffffff)
    position = 0, 180
    halign = center
    valign = center
}
label {
    monitor =
    text = cmd[update:60000] date +"%A, %B %d"
    font_size = 20
    color = rgba(ffffffcc)
    position = 0, 115
    halign = center
    valign = center
}
input-field {
    monitor =
    size = 280, 52
    outline_thickness = 1
    dots_size = 0.22
    rounding = 16
    outer_color = rgba(ffffff55)
    inner_color = rgba(181825bb)
    font_color = rgba(ffffffff)
    placeholder_text = Password
    position = 0, -90
    halign = center
    valign = center
}
